#!/bin/bash

xa -l toc -o ./vic/archivist.bin ./src/VICfiction.asm ./src/TheArchivist.story.asm
printf "\x00\x20" | cat - ./vic/archivist.bin > ./vic/archivist.prg
cp ./vic/archivist.prg ~/vic20/archivist
xa -o ./vic/autostart.bin ./src/autostart.asm
cat ./vic/autostart.bin ./src/jolly.bin | head -c 8192 > ./vic/autostart.eep
printf "\x00\xa0" | cat - ./vic/autostart.bin > ~/vic20/autostart.prg

# Build ROM for Jolly Cartridge
# So, block 1 goes to $e000, block 2 goes to $c000, block 3 goes to $6000
# Autostart for $a000 goes to $4000

# Split the binary file up into three parts
cat ./vic/archivist.bin ./src/jolly.bin | head -c 24576 > ./vic/block1-2-3.bin
cat ./vic/block1-2-3.bin | head -c 8192  > ./vic/block1.bin
cat ./vic/block1-2-3.bin | head -c 16384 > ./vic/block1-2.bin
cat ./vic/block1-2.bin   | tail -c 8192  > ./vic/block2.bin
cat ./vic/block1-2-3.bin | tail -c 8192  > ./vic/block3.bin
rm ./vic/block1-2.bin
rm ./vic/block1-2-3.bin

# Make 16k padding and autostart
cat ./src/jolly.bin | head -c 16384 > ./16k
cat ./vic/autostart.bin ./16k | head -c 8192 > ./vic/autostart.eep

# Generate entire Jolly Cartridge image
#    0-4       $4000                $6000        8-c       $c000            $e000
cat ./16k ./vic/autostart.eep  ./vic/block3.bin ./16k ./vic/block2.bin ./vic/block1.bin > ./vic/archivist.eep
rm ./16k

